import type { Metadata } from "next";
import "./globals.css";
import Providers from "./providers";
import ClientContentWrapper from "../components/ClientContentWrapper";

import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
config.autoAddCss = false;

export const metadata: Metadata = {
  title: "Gym Exercise Manager",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <ClientContentWrapper>
            {children}
          </ClientContentWrapper>
        </Providers>
      </body>
    </html>
  );
}
